# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  black: "#262B44"
  blue: "#4B95E9"
  green: "#59C9A5"
  orange: "#F07623"
  red: "#D81E5B"
  white: "#E0DEF4"
  yellow: "#F3AE35"
transient_prompt:
  template: 〉
  foreground: magenta
  background: transparent
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
      style: full
    template: "{{ .Path }} "
    foreground: green
    background: transparent
    type: path
    style: plain
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: ⟩
    foreground: blue
    background: transparent
    type: text
    style: plain
version: 3
final_space: true
